### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by joshbot**

### CODE REVIEW

**Comment by sebmck** [comment]
`$ make bootstrap` in `.travis.yml` `before_script` is necessary.

**Comment by tricknotes** [comment]
Thanks, @sebmck .
It will land on https://github.com/babel/ruby-babel-transpiler/pull/152 .

**Comment by sebmck** [comment]
Awesome! Thanks @tricknotes and @josh for your hard work!

On Friday, 3 April 2015, Ryunosuke SATO <notifications@github.com> wrote:

> Closed #147 <https://github.com/babel/ruby-babel-transpiler/pull/147> via
> #152 <https://github.com/babel/ruby-babel-transpiler/pull/152>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/ruby-babel-transpiler/pull/147#event-272435348>.
>


-- 
Sebastian McKenzie

**Comment by tricknotes** [comment]
Thanks too @sebmck !
I'm happy to meet a new version of babel :heart:

**Comment by josh** [comment]
:tada:

**Pull request closed without merging**
