### PR TITLE
Upgrade to Babel v6.26.3

### LINKED ISSUE #300: Upgrade to Babel v6.26.3?
Any plans to upgrade to Babel v6.26.3?

### PR DESCRIPTION
**Pull request by pedrofurtado**
Closes #300

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@josh @tricknotes Any news?

**Comment by pedrofurtado** [comment]
@josh @tricknotes Any news? :thinking:

**Comment by pedrofurtado** [comment]
@josh @tricknotes @kittens @danielma ?

**Comment by brauliobo** [comment]
@pedrofurtado where is your repo? seems deleted

**Pull request closed without merging**
