### PR TITLE
Update RubyGems API key

### PR DESCRIPTION
**Pull request by josh**
Switches over to shared [babel](https://rubygems.org/profiles/babel) user.

Just need to keep an eye on the next travis build release to make sure that goes smoothly.

/cc @tricknotes @thejameskyle

### CODE REVIEW

**Comment by thejameskyle** [comment]
Cool, thanks

**Comment by tricknotes** [comment]
Thanks dude!

**Comment by tricknotes** [comment]
It seems working well: https://rubygems.org/gems/babel-source

**Comment by josh** [comment]
:tada:

**Pull request merged**
