### PR TITLE
Release 5.0.0-beta1

### PR DESCRIPTION
**Pull request by tricknotes**
If this is OK, I'll release 5.0.0-beta2and 5.0.0-beta3.

### CODE REVIEW

**Comment by tricknotes** [comment]
rubygems requires `.` separated version:
``` diff
- 5.0.0-beta1
+ 5.0.0-beta1
```

Otherwise, `pre` will be inserted in version: `5.0.0.pre.beta1`

**Comment by josh** [comment]
:+1:

**Comment by josh** [comment]
I think the `test-gem` script may have to be updated too.

Reran the build and its failing on

```
Could not find gem 'babel-source (= 5.0.0.pre.beta1) ruby' in the gems available
```

**Comment by tricknotes** [comment]
Thanks @josh .
I'll try it.

**Comment by josh** [comment]
Okay @tricknotes, maybe try one last rebase :wink:

**Comment by tricknotes** [comment]
Thanks @josh .
just rebased.

**Comment by tricknotes** [comment]
And removed `[WIP]` from PR title.

**Comment by josh** [comment]
:green_heart:

**Comment by tricknotes** [comment]
I send a new PR for other beta versions https://github.com/babel/ruby-babel-transpiler/pull/143

**Comment by tricknotes** [comment]
hmm...

> skipping deploy

https://travis-ci.org/babel/ruby-babel-transpiler/jobs/56448320#L130

**Comment by tricknotes** [comment]
Oops, I should see https://travis-ci.org/babel/ruby-babel-transpiler/jobs/56448319

> ERROR:  While executing gem ... (Gem::Package::FormatError)
No such file or directory - tmp/vendor/cache/babel-source-5.0.0-beta1.gem

I'll fix now.

**Pull request merged**
